config/routes.rb
FantasySportsCalculator::Application.routes.draw do
  devise_for :users 
  resources :users do
    resources :calculate, only: :index
    resources :football_leagues
    resources :basketball_leagues
    resources :baseball_leagues
    resources :soccer_leagues
    resources :hockey_leagues
    resources :football_players
    resources :football_teams
  end
  root :to => "home#index"

end

app/controllers/calculate_controller.rb
class CalculateController < ApplicationController

  def index
    @user = User.find( params[:user_id] )
    @leagues = @user.football_leagues.all
  end


end

app/views/calculate/index.html.erb
<% if @leagues.count == 0 %>
  <p id="calculate-text">Please create a league to calculate with.</p>
  <%= link_to "Create a League", new_user_football_league_path(@user), :class => "btn" %>
<% else %>
  <p id="calculate-text">Please select the position of your player</p>
  <br>
  <div class="btn-group pagination-centered span6 offset4">
    <%= link_to "Quarterback", user_football_players_path(current_user, position: "QB"),  :class => "btn" %>
    <%= link_to "Running Back", user_football_players_path(current_user, position: "RB"), :class => "btn" %>
    <%= link_to "Tight End", user_football_players_path(current_user, position: "TE"), :class => "btn" %>
    <%= link_to "Wide Receiver", user_football_players_path(current_user, position: "WR"), :class => "btn" %>
    <%= link_to "Defense/ST", user_football_teams_path(current_user), :class => "btn" %>
    <%= link_to "Kicker", user_football_players_path(current_user, position: "K"), :class => "btn" %>
  </div>
  <br><br><br>
  <div class="span2 offset7 pagination-centered">
    <%= link_to "Back to leagues", user_football_leagues_path(@user), :class => "btn pagination-centered" %>
  </div>
<% end %>