config/routes.rb
FantasySportsCalculator::Application.routes.draw do
  devise_for :users 
  resources :users do
    resources :calculate, only: :index
    resources :football_leagues
    resources :basketball_leagues
    resources :baseball_leagues
    resources :soccer_leagues
    resources :hockey_leagues
    resources :football_players
    resources :football_teams
  end
  root :to => "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name
  # attr_accessible :title, :body
  has_many :user_football_leagues
  has_many :football_leagues, through: :user_football_leagues
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find( params[:id] )
  end

end

app/views/users/show.html.erb
<% if @user.sign_in_count > 1 %>
  <h2 class="profile-text"><%= "Welcome back, #{@user.first_name.capitalize}!" %></h2>
<% else %>
  <h2 class="profile-text"><%= "Welcome, #{@user.first_name}!" %></h2>
<% end %>
<p class="profile-text">Here are the sports you can calculate for. Pick one and start calculating!</p>
<div class="btn-group pagination-centered" style="margin-left: 35%">
  <%= link_to "Football", user_football_leagues_path(current_user), :class => "btn" %>
  <%= link_to "Basketball", user_basketball_leagues_path(current_user), :class => "btn disabled" %>
  <%= link_to "Baseball", user_baseball_leagues_path(current_user), :class => "btn disabled" %>
  <%= link_to "Soccer", user_soccer_leagues_path(current_user), :class => "btn disabled" %>
  <%= link_to "Hockey", user_hockey_leagues_path(current_user), :class => "btn disabled" %>
</div>