config/routes.rb
FantasySportsCalculator::Application.routes.draw do
  devise_for :users 
  resources :users do
    resources :calculate, only: :index
    resources :football_leagues
    resources :basketball_leagues
    resources :baseball_leagues
    resources :soccer_leagues
    resources :hockey_leagues
    resources :football_players
    resources :football_teams
  end
  root :to => "home#index"

end

app/models/football_league.rb
class FootballLeague < ActiveRecord::Base
  attr_accessible :name, :pass_td, :pass_yards, :int, :pass_2pt 
  attr_accessible :rush_td, :rush_yards, :rush_2pt
  attr_accessible :rec_td, :rec_yards, :rec_2pt
  attr_accessible :fg_made, :fg_missed, :pat_made
  attr_accessible :kick_td, :punt_td, :int_td, :block_kick_td, :fumb_td, :fumb_lost, :def_sack, :def_block_kick, :def_fumb, :def_int, :def_safety, :pts_all_0, :pts_all_6, :pts_all_13, :pts_all_17, :pts_all_27, :pts_all_34, :pts_all_45, :pts_all_46
  has_many :user_football_leagues, :dependent => :delete_all
  has_many :users, through: :user_football_leagues
  validates :name, :presence => true
end

app/controllers/football_leagues_controller.rb
class FootballLeaguesController < ApplicationController

  def index
    @user = current_user
    @football_leagues = @user.football_leagues.all
  end

  def new
    @football_league = FootballLeague.new
  end

  def create
    @football_league = FootballLeague.create( params[:football_league] )
    if @football_league.save
      UserFootballLeague.create(user_id: current_user.id, football_league_id: FootballLeague.last.id)
      redirect_to :action => "index"
    else
      flash[:notice] = @football_league.errors.full_messages.join
      redirect_to :action => "new"
    end
  end

  def show
    @football_league = FootballLeague.find( params[:id] )
  end

  def edit
    @football_league = current_user.football_leagues.find( params[:id] )
  end

  def update
    @football_league = FootballLeague.find( params[:id] )
    if @football_league.update_attributes( params[:football_league] )
      redirect_to user_football_league_url(current_user, @football_league)
    else
      flash[:notice] = @football_league.errors.full_messages.join
      redirect_to edit_user_football_league_path(current_user, @football_league)
    end
  end

  def destroy
    @football_league = FootballLeague.find( params[:id] )
    @football_league.destroy
    redirect_to :action => "index"
  end


end

app/views/football_leagues/_league-form.html.erb
<%= form_for [current_user, @football_league] do |f| %>
  <%= f.label :name, "Name"  %>
  <%= f.text_field :name %>
  <div class="row-fluid">
      <div class="span3">
        <h3>Pass</h3>
        <%= f.label :pass_td, "Touchdown" %>
        <%= f.number_field :pass_td %>
        <%= f.label :pass_yards, "Every 25 Yards" %>
        <%= f.number_field :pass_yards %>
        <%= f.label :int, "Interception" %>
        <%= f.number_field :int %>
        <%= f.label :pass_2pt, "2 point conversion" %>
        <%= f.number_field :pass_2pt %>
      </div>
      <div class="span3">
        <h3>Rush</h3>
        <%= f.label :rush_td, "Touchdown" %>
        <%= f.number_field :rush_td %>
        <%= f.label :rush_yards, "Every 10 Yards" %>
        <%= f.number_field :rush_yards %>
        <%= f.label :rush_2pt, "2 point conversion" %>
        <%= f.number_field :rush_2pt %>
      </div>
      <div class="span3">
        <h3>Receiving</h3>
        <%= f.label :rec_td, "Touchdown" %>
        <%= f.number_field :rec_td %>
        <%= f.label :rec_yards, "Every 10 Yards" %>
        <%= f.number_field :rec_yards %>
        <%= f.label :rec_2pt, "2 point conversion" %>
        <%= f.number_field :rec_2pt %>
      </div>
      <div class="span3">
        <h3>Kicking</h3>
        <%= f.label :fg_made, "Made Field Goal" %>
        <%= f.number_field :fg_made %>
        <%= f.label :fg_missed, "Missed Field Goal" %>
        <%= f.number_field :fg_missed %>
        <%= f.label :pat_made, "Made PAT" %>
        <%= f.number_field :pat_made %>
      </div>
  </div>
  <div class="row-fluid">
      <div class="span3">
        <h3>Miscellaneous</h3>
        <%= f.label :kick_td, "Kick Return TD" %>
        <%= f.number_field :kick_td %>
        <%= f.label :punt_td, "Punt Return TD" %>
        <%= f.number_field :punt_td %>
        <%= f.label :int_td, "Interception Return TD" %>
        <%= f.number_field :int_td %>
        <%= f.label :block_kick_td, "Blocked Kick/Punt Return TD" %>
        <%= f.number_field :block_kick_td %>
        <%= f.label :fumb_td, "Fumble Return TD" %>
        <%= f.number_field :fumb_td %>
        <%= f.label :fumb_lost, "Fumble Lost" %>
        <%= f.number_field :fumb_lost %>
      </div>
      <h3>Defense/Special Teams</h3>
      <div class="span3">
        <%= f.label :def_sack, "Each Sack" %>
        <%= f.number_field :def_sack %>
        <%= f.label :def_block_kick, "Blocked Kick/Punt/PAT" %>
        <%= f.number_field :def_block_kick %>
        <%= f.label :def_fumb, "Fumble Recovery" %>
        <%= f.number_field :def_fumb %>
        <%= f.label :def_int, "Each Interception" %>
        <%= f.number_field :def_int %>
        <%= f.label :def_safety, "Each Safety" %>
        <%= f.number_field :def_safety %>
      </div>
      <div class="span3">
        <%= f.label :pts_all_0, "0 points allowed" %>
        <%= f.number_field :pts_all_0 %>
        <%= f.label :pts_all_6, "1-6 points allowed" %>
        <%= f.number_field :pts_all_6 %>
        <%= f.label :pts_all_13, "7-13 pints allowed" %>
        <%= f.number_field :pts_all_13 %>
        <%= f.label :pts_all_17, "14-17 points allowed" %>
        <%= f.number_field :pts_all_17 %>
        <%= f.label :pts_all_27, "18-27 points allowed" %>
        <%= f.number_field :pts_all_27 %>
        <%= f.label :pts_all_34, "28-34 points allowed" %>
        <%= f.number_field :pts_all_34 %>
        <%= f.label :pts_all_45, "35-45 points allowed" %>
        <%= f.number_field :pts_all_45 %>
        <%= f.label :pts_all_46, "46+ points allowed" %>
        <%= f.number_field :pts_all_46 %>
      </div>
  </div>
  <%= f.submit "Submit" %>
<% end %>

app/views/football_leagues/_league-show-tables.html.erb
<div class="row-fluid">
  <div class="span5 offset1">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>Pass</th>
        </tr>
      </thead>
      <tr>
        <td>Touchdown</td>
        <td><%= @football_league.pass_td %></td>
      </tr>
      <tr>
        <td>Every 25 Yards</td>
        <td><%= @football_league.pass_yards %></td>
      </tr>
      <tr>
        <td>Interception</td>
        <td><%= @football_league.int %></td>
      </tr>
      <tr>
        <td>2 point conv</td>
        <td><%= @football_league.pass_2pt %></td>
      </tr>
    </table>
  </div>
  <div class="span5">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>Rush</th>
        </tr>
      </thead>
      <tr>
        <td>Touchdown</td>
        <td><%= @football_league.rush_td %></td>
      </tr>
      <tr>
        <td>Every 10 Yards</td>
        <td><%= @football_league.rush_yards %></td>
      </tr>
      <tr>
        <td>2 point conv</td>
        <td><%= @football_league.rush_2pt %></td>
      </tr>
    </table>
  </div>
</div>
<div class="row-fluid">
  <div class="span5 offset1">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>Receiving</th>
        </tr>
      </thead>
      <tr>
        <td>Touchdown</td>
        <td><%= @football_league.rec_td %></td>
      </tr>
      <tr>
        <td>Every 10 Yards</td>
        <td><%= @football_league.rec_yards %></td>
      </tr>
      <tr>
        <td>2 point conv</td>
        <td><%= @football_league.rec_2pt %></td>
      </tr>
    </table>
  </div>
  <div class="span5">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>Kicking</th>
        </tr>
      </thead>
      <tr>
        <td>Made Field Goal</td>
        <td><%= @football_league.fg_made %></td>
      </tr>
      <tr>
        <td>Missed Field Goal</td>
        <td><%= @football_league.fg_missed %></td>
      </tr>
      <tr>
        <td>Made PAT</td>
        <td><%= @football_league.pat_made %></td>
      </tr>
    </table>
  </div>
</div>
<div class="row-fluid">
  <div class="span5 offset1">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>Miscellaneous</th>
        </tr>
      </thead>
      <tr>
        <td>Kick Return TD</td>
        <td><%= @football_league.kick_td %></td>
      </tr>
      <tr>
        <td>Punt Return TD</td>
        <td><%= @football_league.punt_td %></td>
      </tr>
      <tr>
        <td>Blocked Kick/Punt Return TD</td>
        <td><%= @football_league.block_kick_td %></td>
      </tr>
      <tr>
        <td>Interception Return TD</td>
        <td><%= @football_league.int_td %></td>
      </tr>
      <tr>
        <td>Fumble Return TD</td>
        <td><%= @football_league.fumb_td %></td>
      </tr>
      <tr>
        <td>Fumble Lost</td>
        <td><%= @football_league.fumb_lost %></td>
      </tr>
    </table>
  </div>
  <div class="span5">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>Defense/Special Teams</th>
        </tr>
      </thead>
      <tr>
        <td>Each Sack</td>
        <td><%= @football_league.def_sack %></td>
      </tr>
      <tr>
        <td>Each Interception</td>
        <td><%= @football_league.def_int %></td>
      </tr>
      <tr>
        <td>Fumble Recovery</td>
        <td><%= @football_league.def_fumb %></td>
      </tr>
      <tr>
        <td>Blocked Kick/Punt/PAT</td>
        <td><%= @football_league.def_block_kick %></td>
      </tr>
      <tr>
        <td>Each Safety</td>
        <td><%= @football_league.def_safety %></td>
      </tr>
      <tr>
        <td>0 points allowed</td>
        <td><%= @football_league.pts_all_0 %></td>
      </tr>
      <tr>
        <td>1-6 points allowed</td>
        <td><%= @football_league.pts_all_6 %></td>
      </tr>
      <tr>
        <td>7-13 points allowed</td>
        <td><%= @football_league.pts_all_13 %></td>
      </tr>
      <tr>
        <td>14-17 points allowed</td>
        <td><%= @football_league.pts_all_17 %></td>
      </tr>
      <tr>
        <td>18-27 points allowed</td>
        <td><%= @football_league.pts_all_27 %></td>
      </tr>
      <tr>
        <td>28-34 points allowed</td>
        <td><%= @football_league.pts_all_34 %></td>
      </tr>
      <tr>
        <td>35-45 points allowed</td>
        <td><%= @football_league.pts_all_45 %></td>
      </tr>
      <tr>
        <td>46+ points allowed</td>
        <td><%= @football_league.pts_all_46 %></td>
      </tr>
    </table>
  </div>
</div>

app/views/football_leagues/edit.html.erb
<h2>Edit</h2>
<%= render "league-form" %>

app/views/football_leagues/index.html.erb
<% if @football_leagues.empty? %>
    <h4 class="league-index-text"><%= "You have no Leagues, please click Add to create a league" %></h4>
<% else %>
  <h3 class="league-index-text">Here are your Football Leagues!</h3>
  <% @football_leagues.each do |league| %>
    <div class="pagination-centered text-center" id="league-list">
      <%= link_to league.name, user_football_league_path(@user, league) %>
    </div>
  <% end %>
<% end %>
<div class="btn-group pagination-centered span6 offset5" id="league-index-btns">
  <%= link_to "Add", new_user_football_league_path(@user), :class => "btn" %>
  <%= link_to "Calculate", user_calculate_index_path(@user), :class => "btn" %>
</div>

app/views/football_leagues/new.html.erb
<h2>Create New Football League</h2>
<%= render "league-form" %>

app/views/football_leagues/show.html.erb
<h2 class="pagination-centered"><%= @football_league.name.upcase %></h2>
<div class="container">
  <%= render "league-show-tables" %>
  <div class="span12 pagination-centered" >
    <%= link_to "Back to List", user_football_leagues_path(current_user), :class => "btn" %>
    <%= link_to "Edit", edit_user_football_league_path(@football_league), :class => "btn" %>
    <%= link_to "Delete",[current_user, @football_league], :method => :delete, :class => "btn" %>
    <%= link_to "Calculate", user_calculate_index_path(current_user), :class => "btn" %>
  </div>
</div>