config/routes.rb
FantasySportsCalculator::Application.routes.draw do
  devise_for :users 
  resources :users do
    resources :calculate, only: :index
    resources :football_leagues
    resources :basketball_leagues
    resources :baseball_leagues
    resources :soccer_leagues
    resources :hockey_leagues
    resources :football_players
    resources :football_teams
  end
  root :to => "home#index"

end

app/models/football_player.rb
require './lib/interface'
class FootballPlayer < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :position, :player_id
  include Interface
  def profile(id)
    player_profile(id)
  end

  def stats(year, week, id)
    player_stats(year, week, id)
  end

  def scores(stats, league)
    pass = pass_score(stats, league)
    rush = rush_score(stats, league)
    rec = rec_score(stats, league)
    kick = kick_score(stats, league)
    misc = misc_score(stats, league)
    total = pass + rush + rec + kick + misc
    total
  end

  def pass_score(stats, league)
    td_score = stats["PassingTouchdowns"].to_i * league.pass_td
    yards_score = (stats["PassingYards"].to_i / 25) * league.pass_yards
    int_score = stats["PassingInterceptions"].to_i * league.int
    two_pt_score = stats["TwoPointConversionPasses"].to_i * league.pass_2pt
    total = td_score + yards_score + two_pt_score + int_score
    total
  end

  def rush_score(stats, league)
    td_score = stats["RushingTouchdowns"].to_i * league.rush_td
    yards_score = (stats["RushingYards"].to_i / 10) * league.rush_yards
    two_pt_score = stats["TwoPointConversionRuns"].to_i * league.rush_2pt
    total = td_score + yards_score + two_pt_score
    total
  end

  def rec_score(stats, league)
    td_score = stats["ReceivingTouchdowns"].to_i * league.rec_td
    yards_score = (stats["ReceivingYards"].to_i / 10) * league.rec_yards
    two_pt_score = stats["TwoPointConversionReceptions"].to_i * league.rec_2pt
    total = td_score + yards_score + two_pt_score
    total
  end

  def kick_score(stats, league)
    fg_miss = stats["FieldGoalsAttempted"].to_i - stats["FieldGoalsMade"].to_i
    pat_miss = stats["ExtraPointsAttempted"].to_i - stats["ExtraPointsMade"].to_i
    fgmade_score = stats["FieldGoalsMade"].to_i * league.fg_made
    fgmiss_score = (fg_miss * league.fg_missed) + (pat_miss * league.fg_missed)
    patmade_score = stats["ExtraPointsMade"].to_i * league.pat_made
    total = fgmade_score + fgmiss_score + patmade_score
    total
  end

  def kick_td(stats, league)
    kick_stat = stats["KickReturnTouchdowns"]
    kick_rule = league.kick_td
    score = kick_stat * kick_rule
    score
  end

  def fum_td(stats, league)
    fum_stat = stats["FumbleReturnTouchdowns"]
    fum_rule = league.fumb_td
    score = fum_stat * fum_rule
    score    
  end

  def punt_td(stats, league)
    punt_stat = stats["PuntReturnTouchdowns"]
    punt_rule = league.punt_td
    score = punt_stat * punt_rule
    score    
  end

  def int_td(stats, league)
    int_stat = stats["InterceptionReturnTouchdowns"]
    int_rule = league.int_td
    score = int_stat * int_rule
    score
  end

  def block_td(stats, league)
    block_stat = stats["BlockedKickReturnTouchdowns"]
    block_rule = league.block_kick_td
    score = block_stat * block_rule
    score
  end

  def fum_lost(stats, league)
    fum_stat = stats["FumblesLost"]
    fum_rule = league.fumb_lost
    score = fum_stat * fum_rule
    score    
  end

  def misc_score(stats, league)
    kick = kick_td(stats, league)
    fumtd = fum_td(stats, league)
    punt = punt_td(stats, league)
    int = int_td(stats, league)
    block = block_td(stats, league)
    fumlost = fum_lost(stats, league)
    score = kick + fumtd + punt + int + block + fumlost
    score 
  end
end

app/controllers/football_players_controller.rb
class FootballPlayersController < ApplicationController
  before_filter :check_for_params

  def index
    @players = @param.all
  end

  def show
    @user = current_user
    @player = FootballPlayer.find( params[:id] )
    @profile = @player.profile(@player.player_id)
  end

  def create
    @user = User.find(params[:user_id])
    @player = FootballPlayer.where(player_id: params[:stats][:player_id]).first
    @profile = @player.profile(@player.player_id)
    @stats = @player.stats(params[:stats][:year], params[:stats][:week], params[:stats][:player_id])
  end

  private
  def check_for_params
    if params[:position]
      @param = FootballPlayer.where( position: params[:position] )
    else
      @param = FootballPlayer
    end
  end
end

app/views/football_players/_calculate-stats-tables.html.erb
<% team = FootballTeam.where(abbr_name: @stats["Opponent"]).first %>
<h4>Opponent: <%= team.full_name %></h4>
<% if @player.position == "K" %>
  <table class="table table-hover table-bordered">
    <thead class="text-center">
      <tr>
        <th>FGM</th>
        <th>FGA</th>
        <th>FG%</th>
        <th>PAT</th>
      </tr>
    </thead>
    <tr>
      <th><%= @stats["FieldGoalsMade"] %></th>
      <th><%= @stats["FieldGoalsAttempted"] %></th>
      <th><%= @stats["FieldGoalPercentage"] %></th>
      <th><%= "#{@stats["ExtraPointsMade"]}/#{@stats["ExtraPointsAttempted"]}" %></th>
    </tr>
  </table>
<% elsif @player.position == "QB" %>
  <table class="table table-hover table-bordered">
    <thead class="text-center">
      <tr>
        <th class="text-center">Passing</th>
      </tr>
      <tr>
        <th>Cmp</th>
        <th>Att</th>
        <th>Cmp%</th>
        <th>Yds</th>
        <th>Lng</th>
        <th>TD</th>
        <th>Int</th>
      </tr>
    </thead>
    <tr>
      <td><%= @stats["PassingCompletions"] %></td>
      <td><%= @stats["PassingAttempts"] %></td>
      <td><%= @stats["PassingCompletionPercentage"] %></td>
      <td><%= @stats["PassingYards"] %></td>
      <td><%= @stats["PassingLong"] %></td>
      <td><%= @stats["PassingTouchdowns"] %></td>
      <td><%= @stats["PassingInterceptions"] %></td>
    </tr>
  </table>
  <table class="table table-hover table-bordered">
    <thead class="text-center">
      <tr>
        <th class="text-center">Rushing</th>
      </tr>
      <tr>
        <th>Att</th>
        <th>Yds</th>
        <th>Avg</th>
        <th>Lng</th>
        <th>TD</th>
      </tr>
    </thead>
    <tr>
      <td><%= @stats["RushingAttempts"] %></td>
      <td><%= @stats["RushingYards"] %></td>
      <td><%= @stats["RushingYardsPerAttempt"] %></td>
      <td><%= @stats["RushingLong"] %></td>
      <td><%= @stats["RushingTouchdowns"] %></td>
    </tr>
  </table>
<% else %>
  <table class="table table-hover table-bordered">
    <thead class="text-center">
      <tr>
        <th class="text-center">Rushing</th>
      </tr>
      <tr>
        <th>Att</th>
        <th>Yds</th>
        <th>Avg</th>
        <th>Lng</th>
        <th>TD</th>
      </tr>
    </thead>
    <tr>
      <td><%= @stats["RushingAttempts"] %></td>
      <td><%= @stats["RushingYards"] %></td>
      <td><%= @stats["RushingYardsPerAttempt"] %></td>
      <td><%= @stats["RushingLong"] %></td>
      <td><%= @stats["RushingTouchdowns"] %></td>
    </tr>
  </table>
  <table class="table table-hover table-bordered">
    <thead class="text-center">
      <tr>
        <th class="text-center">Receiving</th>
      </tr>
      <tr>
        <th>Rec</th>
        <th>Yds</th>
        <th>Avg</th>
        <th>Lng</th>
        <th>TD</th>
      </tr>
    </thead>
    <tr>
      <td><%= @stats["Receptions"] %></td>
      <td><%= @stats["ReceivingYards"] %></td>
      <td><%= @stats["ReceivingYardsPerReception"] %></td>
      <td><%= @stats["ReceivingLong"] %></td>
      <td><%= @stats["ReceivingTouchdowns"] %></td>
    </tr>
  </table>
<% end %>

app/views/football_players/_player-info.html.erb
<% team = FootballTeam.where(abbr_name: @profile["CurrentTeam"]).first %>
<p>#<%= @profile["Number"] %> <%= @profile["Position"] %> | <%= @profile["Height"] %> <%= @profile["Weight"] %> lbs. | <%= team.full_name %></p>
<p>Birth Date: <%= @profile["BirthDateString"] %></p>
<p>Age: <%= @profile["Age"] %></p>
<p>College: <%= @profile["College"] %></p>
<p>Experience: <%= @profile["ExperienceString"] %></p>

app/views/football_players/_profile-stats.html.erb
<p><%= @profile["PlayerSeason"]["Season"] %> Season</p>
<% if @player.position == "QB" %>
  <table class="table table-bordered">
    <thead>
      <th>Rating</th>
      <th>Yards</th>
      <th>TD</th>
    </thead>
    <tr>
      <td><%= @profile["PlayerSeason"]["PassingRating"] %></td>
      <td><%= @profile["PlayerSeason"]["PassingYards"] %></td>
      <td><%= @profile["PlayerSeason"]["PassingTouchdowns"] %></td>
    </tr>
  </table>
<% elsif @player.position == "RB" %>
  <table class="table table-bordered">
    <thead>
      <th>Carries</th>
      <th>Yards</th>
      <th>TD</th>
    </thead>
    <tr>
      <td><%= @profile["PlayerSeason"]["RushingAttempts"] %></td>
      <td><%= @profile["PlayerSeason"]["RushingYards"] %></td>
      <td><%= @profile["PlayerSeason"]["RushingTouchdowns"] %></td>
    </tr>
  </table>
<% elsif @player.position == "K" %>
  <table class="table table-bordered">
    <thead>
      <th>FGM</th>
      <th>XPM</th>
    </thead>
    <tr>
      <td><%= @profile["PlayerSeason"]["FieldGoalsMade"] %></td>
      <td><%= @profile["PlayerSeason"]["ExtraPointsMade"] %></td>
    </tr>
  </table>
<% else %>
  <table class="table table-bordered">
    <thead>
      <th>Rec</th>
      <th>Yards</th>
      <th>TD</th>
    </thead>
    <tr>
      <td><%= @profile["PlayerSeason"]["Receptions"] %></td>
      <td><%= @profile["PlayerSeason"]["ReceivingYards"] %></td>
      <td><%= @profile["PlayerSeason"]["ReceivingTouchdowns"] %></td>
    </tr>
  </table>
<% end %>

app/views/football_players/create.html.erb
<% if @stats.has_key?("error") %>
  <p><%= @stats["error"] %></p>
<% else %>
  <h2><%= @player.first_name + " " + @player.last_name %></h2>
  <div class="row-fluid" id="profile">
    <img id="profile-img" src="<%= @profile['PhotoUrl'] %>" />
    <div id="player-info" class="span4">
      <%= render "player-info" %>
      <ul id="score-list">
        <% @user.football_leagues.each do |league| %>
          <li><strong><%= "#{league.name.upcase} score is #{@player.scores(@stats, league)}" %></strong></li>
        <% end %>
      </ul>
    </div>
    <div class="span6">
      <%= render "calculate-stats-tables" %>
    </div>
  </div>
<% end %>
<div class="btn-group">
  <%= link_to "Back to player select", user_calculate_index_path(@user), :class => "btn" %>
  <%= link_to "Back to user profile", user_path(@user), :class => "btn" %>
  <%= link_to "Back to player profile", user_football_player_path(@user, @player), :class => "btn" %>
</div>

app/views/football_players/index.html.erb
<ul>
<% @players.each do |player| %>
  <li><%= link_to player.first_name + " " + player.last_name, user_football_player_path(current_user, player) %></li>
<% end %>
</ul>

app/views/football_players/show.html.erb
<h2><%= @player.first_name + " " + @player.last_name %></h2>
<div class="row-fluid" id="profile">
  <img id="profile-img" src="<%= @profile['PhotoUrl'] %>" />
  <div id="player-info" class="span4">
    <%= render "player-info" %>
  </div>
  <div class="span4">
    <%= render "profile-stats" %>
  </div>
</div>
<div id="stats"></div>

<%= form_tag("/users/#{@user.id}/football_players", :method => "post") do %>
  <%= text_field_tag("stats[year]", nil, :placeholder => "Year") %>
  <%= text_field_tag("stats[week]", nil, :placeholder => "Week") %>
  <%= hidden_field_tag("stats[player_id]", "#{@player.player_id}") %>
  <%= submit_tag "Calculate" %>
<% end %>
<%= link_to "Back to Player List", user_calculate_index_path(@user), :class => "btn" %>